---
title : '통계학습 2주차 과제'
author : '문성일'
date : '9/14/2021'
output : html_document
---
# Start

## 설정
$$x,~~ \epsilon,~~ seed$$
```{r}
set.seed(1234)
x = rnorm(100,m=0,sd=1)
e = rnorm(100,m=0,sd=1)
```

## Problem1
$$y=x+\epsilon, \epsilon \sim N(0,1), ~X \sim N(0,1)$$

## Problem2
$$y=x*(1-x)+\epsilon, \epsilon \sim N(0,1), ~X \sim N(0,1)$$

```{r}
y1 = x+e #Problem 1
y2 = x*(1-x)+e #problem 2
```

## Linear model

### 함수만들기
```{r}
linear_function<-function(x,y){
  x = as.matrix(x)
  y = as.matrix(y)
  
  one_vector = rep(1,dim(x)[1])
  
  x = cbind(one_vector,x)
  
  Bhat = solve(t(x)%*%x)%*%(t(x)%*%y)
  fitted_value = x%*%Bhat
  print(head(fitted_value))
}
```

### Problem1 결과값
```{r}
linear_function(x,y1)
```

### Problem2 결과값
```{r}
linear_function(x,y2)
```

## KNN

### 함수만들기
```{r}
# knn function
knn_function <- function(x,y,k){
  
  #normalization function
  normalize <- function(x){
    if(is.matrix(x)==F){
      x_bar = mean(x)
      x_sd = sd(x)
      x_normal = (x-x_bar)/x_sd
    }else {
      x_bar <- apply(x,2,mean)
      x_sd <- apply(x,2,sd)
      x_normal <- matrix(rep(0,dim(x)[1]*dim(x)[2]),nrow = dim(x)[1],ncol = dim(x)[2])
      
      for(i in 1:dim(x)[2]){
        x_normal[,i]<-(x[,i] - x_bar[i])/x_sd[i]
        x<-x_normal
          return(x)
      }
    }
  }
  
  # eucliden_distance function
  eucliden_distance<- function(x,y){
    sqrt(sum((x-y)^2))
  }
  
  # distance matrix function
  distance_matrix<- function(x){
    if(is.matrix(x)==F){
      n<-length(x)
    }else {
      n<-dim(x)[1]
    }
    distance_result_matrix = matrix(rep(0,n^2),n,n)
    if(is.matrix(x)==F){
      for(i in 1:n){
        for(j in 1:n){
          distance_result_matrix[j,i] = eucliden_distance(x[j],x[i])
        }
      }
    }else {
      for(i in 1:n){
        for(j in 1:n){
          distance_result_matrix[j,i] = eucliden_distance(x[j,],x[i,])
        }
      }
    }
    distance_result_matrix = distance_result_matrix+t(distance_result_matrix)
    return(distance_result_matrix)
  }
  
  dist_matrix <-distance_matrix(normalize(x))
  
  matrix_order <- apply(dist_matrix,1,order)
  
  fitted_value <- c()
  for(q in 1:dim(matrix_order)[1]){
    fitted_value[q] <- mean(y[matrix_order[2:(k+1),q]])
  }
  return(head(fitted_value))
}
```

### Problem1 1-NN결과값
```{r}
knn_function(x,y1,k=1)
```

### Problem1 5-NN결과값
```{r}
knn_function(x,y1,k=1)
```

### Problem1 10-NN결과값
```{r}
knn_function(x,y1,k=10)
```

### Problem2 1-NN결과값
```{r}
knn_function(x,y2,k=1)
```

### Problem2 5-NN결과값
```{r}
knn_function(x,y2,k=5)
```

### Problem2 10-NN결과값
```{r}
knn_function(x,y2,k=10)
```


